pool:
  vmImage: macOS-10.15
trigger:
- buildbranch_osx
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-ros-move-group ros-noetic-leo-msgs ros-noetic-cob-navigation-global
          ros-noetic-sbpl-lattice-planner ros-noetic-pose-follower
      displayName: Build ros-noetic-moveit-ros-move-group ros-noetic-leo-msgs ros-noetic-cob-navigation-global
        ros-noetic-sbpl-lattice-planner ros-noetic-pose-follower
  - job: stage_0_job_1
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-ros-benchmarks ros-noetic-robot-calibration
          ros-noetic-turtlebot3-navigation ros-noetic-moveit-plugins ros-noetic-mbf-costmap-nav
      displayName: Build ros-noetic-moveit-ros-benchmarks ros-noetic-robot-calibration
        ros-noetic-turtlebot3-navigation ros-noetic-moveit-plugins ros-noetic-mbf-costmap-nav
  - job: stage_0_job_2
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-cob-manipulation-msgs
      displayName: Build ros-noetic-cob-manipulation-msgs
- stage: stage_1
  jobs:
  - job: stage_1_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-ros-manipulation ros-noetic-cob-mapping-slam
          ros-noetic-sbpl-recovery ros-noetic-fetch-calibration ros-noetic-turtlebot3
      displayName: Build ros-noetic-moveit-ros-manipulation ros-noetic-cob-mapping-slam
        ros-noetic-sbpl-recovery ros-noetic-fetch-calibration ros-noetic-turtlebot3
  - job: stage_1_job_1
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-move-base-flex ros-noetic-gpp-plugin
      displayName: Build ros-noetic-move-base-flex ros-noetic-gpp-plugin
- stage: stage_2
  jobs:
  - job: stage_2_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-ros-planning-interface ros-noetic-cob-navigation-slam
      displayName: Build ros-noetic-moveit-ros-planning-interface ros-noetic-cob-navigation-slam
- stage: stage_3
  jobs:
  - job: stage_3_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-ros-visualization ros-noetic-moveit-commander
          ros-noetic-moveit-planners-chomp ros-noetic-pincher-arm-moveit-demos ros-noetic-webots-ros
      displayName: Build ros-noetic-moveit-ros-visualization ros-noetic-moveit-commander
        ros-noetic-moveit-planners-chomp ros-noetic-pincher-arm-moveit-demos ros-noetic-webots-ros
- stage: stage_4
  jobs:
  - job: stage_4_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-moveit-setup-assistant ros-noetic-pilz-industrial-motion-testutils
          ros-noetic-panda-moveit-config ros-noetic-moveit-planners ros-noetic-moveit-ros
      displayName: Build ros-noetic-moveit-setup-assistant ros-noetic-pilz-industrial-motion-testutils
        ros-noetic-panda-moveit-config ros-noetic-moveit-planners ros-noetic-moveit-ros
- stage: stage_5
  jobs:
  - job: stage_5_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-pincher-arm-moveit-config ros-noetic-franka-example-controllers
          ros-noetic-moveit-runtime ros-noetic-moveit
      displayName: Build ros-noetic-pincher-arm-moveit-config ros-noetic-franka-example-controllers
        ros-noetic-moveit-runtime ros-noetic-moveit
- stage: stage_6
  jobs:
  - job: stage_6_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-franka-ros
      displayName: Build ros-noetic-franka-ros
